"use client"
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { useState, useEffect } from "react"
import { CartContext } from "@/context/CartContext"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Oysho",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [cartItemState, setCartItemState] = useState([])
  const [totalCartItem, setTotalCartItem] = useState(0)
  const [totalPrice, setTotalPrice] = useState(0)


  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <CartContext.Provider value={{cartItemState, setCartItemState, totalCartItem, setTotalCartItem,totalPrice, setTotalPrice}}>
          {children}
        </CartContext.Provider>
      </body>
    </html>
  );
}
